en:
  errors:
    messages:
      belongs_to: "does not belong to %{value}"